name: Commit and Push
description: Action to save git changes

inputs:
  git_user_email:
    required: true
    description: Email to use on Git commits
    default: windup@users.noreply.github.com
  git_user_name:
    required: true
    description: User name to use on Git commits
    default: Windup
  commit_message:
    required: true
    description: Commit message to be used
    default: Preparing for release
  branch:
    required: true
    default: master
    description: branch to push commits
  working-directory:
    required: true
    default: ${{ github.workspace }}
    description: 'The directory to change into.'

runs:
  using: "composite"
  steps:
    - name: Config Git
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git config --global user.email "$GIT_USER_EMAIL"
        git config --global user.name "$GIT_USER_NAME"
      env:
        GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        GIT_USER_NAME: ${{ inputs.git_user_name }}
    - name: Commit and push
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git commit --allow-empty -a -m "$COMMIT_MESSAGE"
        git push origin HEAD:${{ inputs.branch }}
      env:
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
