name: Publish Javadocs

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The value of the Windup repository Tag"
        required: true
        default: "Ex: 6.0.0.Final"
        type: string

jobs:
  windup-javadocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: windup/windup
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.inputs.release_version }}
          path: windup
      - uses: actions/checkout@v3
        with:
          repository: windup/windup.github.io.git
          token: ${{ secrets.GH_PAT }}
          path: windup-website
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: Generate Javadocs
        working-directory: windup
        run: |
          mvn install -DskipTests
          mvn validate \
          -PjavadocDist \
          -DskipTests \
          -Djavadoc.branding="Windup ${{ github.event.inputs.release_version }} Javadoc"
      - name: Copy Javadocs to website
        run: |
          mkdir -p windup-website/static/javadocs/
          rm -rf windup-website/static/javadocs/
          cp -R windup/target/apidocs/ windup-website/static/javadocs/
          
          cd windup-website && git add -A
      - name: Commit and Push
        uses: windup/windup-pipelines/actions/commit@main
        with:
          working-directory: windup-website
          branch: main
          commit_message: "⬆️ Releasing Javadocs ${{ github.event.inputs.release_version }}"