name: Publish Javadocs

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The value of the Windup repository Tag"
        required: true
        default: "Ex: 6.0.0.Final"
        type: string

jobs:
  windup-javadocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI
        uses: actions/checkout@v3
        with:
          path: ci
      - uses: actions/checkout@v3
        with:
          repository: windup/windup
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.inputs.release_version }}
          path: windup
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: Generate Javadocs
        run: |
          export SETTINGS_XML=$(readlink -f ci/maven/settings.xml)
          
          cd windup
          mvn install -DskipTests -s $SETTINGS_XML
          mvn validate \
          -s $SETTINGS_XML \
          -PjavadocDist \
          -DskipTests \
          -Djavadoc.branding="Windup ${{ github.event.inputs.release_version }} Javadoc"
      - name: Copy Javadocs to gh-pages
        working-directory: windup
        run: |
          mv target/apidocs apidocs/
          mvn clean
          
          git checkout gh-pages
          rm docs/latest
          
          cd docs
          mkdir -p ${{ github.event.inputs.release_version }}
          ln -s ${{ github.event.inputs.release_version }}/ latest
          cd ..
          
          mv apidocs/ docs/latest/javadoc/
          git add docs
      - name: Commit and Push
        uses: windup/windup-pipelines/actions/commit@main
        with:
          working-directory: windup
          branch: gh-pages
          commit_message: "Add ${{ github.event.inputs.release_version }} javadoc"