name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "The value of the version to be released"
        required: true
        default: "Ex: 6.0.0.Final"
        type: string
      next_development_version:
        description: "The value of the next version to be developed"
        required: true
        default: "Ex: 6.1.0-SNAPSHOT"
        type: string
      github_organization:
        description: The GitHub organization of repositories
        required: true
        default: "windup"
        type: string
      registry_organization:
        description: The GitHub organization of repositories
        required: true
        default: "windupeng"
        type: string

jobs:
  windup:
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        echo "Nothing to do"
      after_script: |
        echo "Nothing to do"
      cache_key: windup
      cache_key_to_restore: windup
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-rulesets:
    needs: [ windup ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-rulesets
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${RELEASE_VERSION}<\/version.windup>/g" pom.xml
        git add pom.xml
      after_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${NEXT_DEVELOPMENT_VERSION}<\/version.windup>/g" pom.xml
        git add pom.xml
      cache_key: windup-rulesets
      cache_key_to_restore: windup
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-distribution:
    needs: [ windup-rulesets ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${RELEASE_VERSION}<\/version.windup>/g" pom.xml
        sed -i -e "s/<version.windup-rulesets>.*<\/version.windup-rulesets>/<version.windup-rulesets>${RELEASE_VERSION}<\/version.windup-rulesets>/g" pom.xml
        git add pom.xml
      after_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${NEXT_DEVELOPMENT_VERSION}<\/version.windup>/g" pom.xml
        sed -i -e "s/<version.windup-rulesets>.*<\/version.windup-rulesets>/<version.windup-rulesets>${NEXT_DEVELOPMENT_VERSION}<\/version.windup-rulesets>/g" pom.xml
        git add pom.xml
      cache_key: windup-distribution
      cache_key_to_restore: windup-rulesets
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-web:
    needs: [ windup-distribution ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-web
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${RELEASE_VERSION}<\/version.windup>/g" pom.xml
        sed -i -e "s/<version.windup.cli>.*<\/version.windup.cli>/<version.windup.cli>${RELEASE_VERSION}<\/version.windup.cli>/g" pom.xml
        git add pom.xml
        
        sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
        sed -i -e "s/<version.windup.ruleset>.*<\/version.windup.ruleset>/<version.windup.ruleset>${RELEASE_VERSION}<\/version.windup.ruleset>/g" tsmodelsgen-invocation/pom.xml
        git add tsmodelsgen-invocation/pom.xml
        
        sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${RELEASE_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
        sed -i -e "s/<version.windup.ruleset>.*<\/version.windup.ruleset>/<version.windup.ruleset>${RELEASE_VERSION}<\/version.windup.ruleset>/g" tsmodelsgen-maven-plugin/pom.xml
        git add tsmodelsgen-maven-plugin/pom.xml
      after_script: |
        sed -i -e "s/<version.windup>.*<\/version.windup>/<version.windup>${NEXT_DEVELOPMENT_VERSION}<\/version.windup>/g" pom.xml
        sed -i -e "s/<version.windup.cli>.*<\/version.windup.cli>/<version.windup.cli>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.cli>/g" pom.xml
        git add pom.xml
        
        sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-invocation/pom.xml
        sed -i -e "s/<version.windup.ruleset>.*<\/version.windup.ruleset>/<version.windup.ruleset>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.ruleset>/g" tsmodelsgen-invocation/pom.xml
        git add tsmodelsgen-invocation/pom.xml
        
        sed -i -e "s/<version.windup.core>.*<\/version.windup.core>/<version.windup.core>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.core>/g" tsmodelsgen-maven-plugin/pom.xml
        sed -i -e "s/<version.windup.ruleset>.*<\/version.windup.ruleset>/<version.windup.ruleset>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.ruleset>/g" tsmodelsgen-maven-plugin/pom.xml
        git add tsmodelsgen-maven-plugin/pom.xml
      cache_key: windup-web
      cache_key_to_restore: windup-distribution
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-openshift:
    needs: [ windup-web ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-openshift
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        sed -i -e "s/<version.windup.cli>.*<\/version.windup.cli>/<version.windup.cli>${RELEASE_VERSION}<\/version.windup.cli>/g" cli/pom.xml
        git add cli/pom.xml
        
        sudo apt-get install -y groovy          
        groovy ./build/change_docker_image_tag.groovy ./templates/src/main/resources/web-template-empty-dir-executor.json ${RELEASE_VERSION}
        groovy ./build/change_docker_image_tag.groovy ./templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json ${RELEASE_VERSION}
        
        git add templates/src/main/resources/web-template-empty-dir-executor.json
        git add templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json
      after_script: |
        # Container image creation
        mvn install -DskipTests \
        -Ddocker.name.windup.web=quay.io/${{ github.event.inputs.registry_organization }}/windup-web-openshift:$RELEASE_VERSION \
        -Ddocker.name.windup.web.executor=quay.io/${{ github.event.inputs.registry_organization }}/windup-web-openshift-messaging-executor:$RELEASE_VERSION \
        -Ddocker.name.windup.cli=quay.io/${{ github.event.inputs.registry_organization }}/windup-cli-openshift:$RELEASE_VERSION
        
        docker image push quay.io/${{ github.event.inputs.registry_organization }}/windup-web-openshift:$RELEASE_VERSION
        docker image push quay.io/${{ github.event.inputs.registry_organization }}/windup-web-openshift-messaging-executor:$RELEASE_VERSION
        docker image push quay.io/${{ github.event.inputs.registry_organization }}/windup-cli-openshift:$RELEASE_VERSION
        
        # Prepare next release
        sed -i -e "s/<version.windup.cli>.*<\/version.windup.cli>/<version.windup.cli>${NEXT_DEVELOPMENT_VERSION}<\/version.windup.cli>/g" cli/pom.xml
        git add cli/pom.xml
        
        sudo apt-get install -y groovy          
        groovy ./build/change_docker_image_tag.groovy ./templates/src/main/resources/web-template-empty-dir-executor.json latest
        groovy ./build/change_docker_image_tag.groovy ./templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json latest
        
        git add templates/src/main/resources/web-template-empty-dir-executor.json
        git add templates/src/main/resources/web-template-empty-dir-executor-shared-storage.json
      cache_key: windup-openshift
      cache_key_to_restore: windup-web
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-web-distribution:
    needs: [ windup-openshift-container-images ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-web-distribution
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        echo "Nothing to do"
      after_script: |
        echo "Nothing to do"
      cache_key: windup-web-distribution
      cache_key_to_restore: windup-openshift
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  windup-maven-plugin:
    needs: [ windup-web-distribution ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-maven-plugin
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      before_script: |
        sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${RELEASE_VERSION}<\/version.windupcore>/g" pom.xml
        git add pom.xml
        
        sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${RELEASE_VERSION}<\/version.windupcore>/g" src/it/simple-it/pom.xml
        sed -i -e "s/<version>.*<\/version>/<version>${RELEASE_VERSION}<\/version>/g" src/it/simple-it/pom.xml
        git add src/it/simple-it/pom.xml
        
        sed -i -e "s/<version>.*<\/version>/<version>${RELEASE_VERSION}<\/version>/g" src/test/resources/mojoTestConfig.xml
        git add src/test/resources/mojoTestConfig.xml
        
        sed -i -e "s/<windupVersion>.*<\/windupVersion>/<windupVersion>${RELEASE_VERSION}<\/windupVersion>/g" src/test/resources/mojoTestConfigWithWindupVersion.xml
        git add src/test/resources/mojoTestConfigWithWindupVersion.xml
        
        sed -i -e "s/assertEquals(mojo2.getWindupVersion(), \".*\");/assertEquals(mojo2.getWindupVersion(), \"${RELEASE_VERSION}\");/g" src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
        git add src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
      after_script: |
        sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${NEXT_DEVELOPMENT_VERSION}<\/version.windupcore>/g" pom.xml
        git add pom.xml
        
        sed -i -e "s/<version.windupcore>.*<\/version.windupcore>/<version.windupcore>${NEXT_DEVELOPMENT_VERSION}<\/version.windupcore>/g" src/it/simple-it/pom.xml
        sed -i -e "s/<version>.*<\/version>/<version>${NEXT_DEVELOPMENT_VERSION}<\/version>/g" src/it/simple-it/pom.xml
        git add src/it/simple-it/pom.xml
        
        sed -i -e "s/<version>.*<\/version>/<version>${NEXT_DEVELOPMENT_VERSION}<\/version>/g" src/test/resources/mojoTestConfig.xml
        git add src/test/resources/mojoTestConfig.xml
        
        sed -i -e "s/<windupVersion>.*<\/windupVersion>/<windupVersion>${NEXT_DEVELOPMENT_VERSION}<\/windupVersion>/g" src/test/resources/mojoTestConfigWithWindupVersion.xml
        git add src/test/resources/mojoTestConfigWithWindupVersion.xml
        
        sed -i -e "s/assertEquals(mojo2.getWindupVersion(), \".*\");/assertEquals(mojo2.getWindupVersion(), \"${NEXT_DEVELOPMENT_VERSION}\");/g" src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
        git add src/test/java/org/jboss/windup/plugin/WindupMojoTest.java
      cache_key: windup-maven-plugin
      cache_key_to_restore: windup-web-distribution
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  
  windup-quickstarts:
    needs: [ windup-maven-plugin ]
    uses: ./.github/workflows/release-template.yml
    with:
      owner: ${{ github.event.inputs.github_organization }}
      repository: windup-quickstarts
      release_version: ${{ github.event.inputs.release_version }}
      next_development_version: ${{ github.event.inputs.next_development_version }}
      jreleaser_file: jreleaser/basic.yml
      skip_maven_release: true # We just need tag repo but not to release to maven central
      before_script: |
        MVN_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        find . -name pom.xml -exec sed -i -e "s/${MVN_VERSION}/${RELEASE_VERSION}/g" {} \;
        git add -A
      after_script: |
        find . -name pom.xml -exec sed -i -e "s/${RELEASE_VERSION}/${NEXT_DEVELOPMENT_VERSION}/g" {} \;
        git add -A
      cache_key: windup-quickstarts
      cache_key_to_restore: windup-maven-plugin
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
