name: Set version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The value of the version to be set"
        required: true
        default: "Ex: 6.2.0-SNAPSHOT"
        type: string

jobs:
  windup:
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup
      version: ${{ github.event.inputs.version }}
      cache_key: windup
      cache_key_to_restore: windup
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-rulesets:
    needs: [ windup ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-rulesets
      version: ${{ github.event.inputs.version }}
      cache_key: windup-rulesets
      cache_key_to_restore: windup
      run_before: |
        setNextVersion_windupRulesets
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-distribution:
    needs: [ windup-rulesets ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-distribution
      version: ${{ github.event.inputs.version }}
      cache_key: windup-distribution
      cache_key_to_restore: windup-rulesets
      run_before:  |
        setNextVersion_windupDistribution
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-web:
    needs: [ windup-distribution ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-web
      version: ${{ github.event.inputs.version }}
      cache_key: windup-web
      cache_key_to_restore: windup-distribution
      run_before:  |
        setNextVersion_windupWeb
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-openshift:
    needs: [ windup-web ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-openshift
      version: ${{ github.event.inputs.version }}
      cache_key: windup-openshift
      cache_key_to_restore: windup-web
      run_before:  |
        setNextVersion_windupOpenshift
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-web-distribution:
    needs: [ windup-openshift ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-web-distribution
      version: ${{ github.event.inputs.version }}
      cache_key: windup-web-distribution
      cache_key_to_restore: windup-openshift
      run_before:  |
        setNextVersion_windupWebDistribution
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-maven-plugin:
    needs: [ windup-web-distribution ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-maven-plugin
      version: ${{ github.event.inputs.version }}
      cache_key: windup-maven-plugin
      cache_key_to_restore: windup-web-distribution
      run_before:  |
        setNextVersion_windupMavenPlugin
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

  windup-quickstarts:
    needs: [ windup-maven-plugin ]
    uses: ./.github/workflows/set-version-template.yml
    with:
      owner: windup
      repository: windup-quickstarts
      version: ${{ github.event.inputs.version }}
      cache_key: windup-quickstarts-plugin
      cache_key_to_restore: windup-maven-plugin
      run_before:  |
        setNextVersion_windupQuickstarts
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
